version: '3'

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

services:
  shadowsocks:
    build: 
      context: ./shadowsocks
      args:
        - PASSWORD=${SHADOWSOCKS_PASSWORD}
    ports: 
      - "8488:8488"
    networks:
      - frontend
      - backend
  golang:
    build:
      context: ./golang
    ports:
      - "8080:8080"
    networks:
      - frontend
      - backend