version: '3'

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

services:
  shadowsocks:
    build: 
      context: ./shadowsocks
      args:
        - PASSWORD=${SHADOWSOCKS_PASSWORD}
    volumes:
      - ${DATA_PATH_HOST}/go/src:/go/src
      - ${DATA_PATH_HOST}/go/bin:/go/bin
      - ${DATA_PATH_HOST}/go/pkg:/go/pkg
    ports: 
      - "${SHADOWSOCKS_PORT}:10086"
    networks:
      - frontend
      - backend
  golang:
    build:
      context: ./golang
    volumes:
      - ./golang/conf:/go/conf
      - ${DATA_PATH_HOST}/golang/storage:/root/storage
    ports:
      - "8080:8080"
    networks:
      - frontend
      - backend
  nginx:
    build:
      context: ./nginx
    volumes:
      - ./logs/nginx/:/var/log/nginx
      - ./nginx/sites/:/etc/nginx/sites-available
      - ./nginx/ssl/:/etc/nginx/ssl
      - ../majsoul-resources/extendRes/:/var/www/files.juehaodiao.xyz/majsoul/extendRes
      - ../majsoul-resources/audio/:/var/www/files.juehaodiao.xyz/majsoul/audio
    depends_on:
        - golang
    ports:
      - "80:80"
      - "443:443"
    networks:
      - frontend
      - backend
  ### MongoDB ##############################################
  mongo:
    build: ./mongo
    ports:
      - "27017:27017"
    volumes:
      - ${DATA_PATH_HOST}/mongo:/data/db
      - ${DATA_PATH_HOST}/mongo_config:/data/configdb
    networks:
      - backend





