version: '3'

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

services:
  shadowsocks:
    build: 
      context: ./shadowsocks
      args:
        - PASSWORD=${SHADOWSOCKS_PASSWORD}
    volumes:
      - ${DATA_PATH_HOST}/go/src:/go/src
      - ${DATA_PATH_HOST}/go/bin:/go/bin
      - ${DATA_PATH_HOST}/go/pkg:/go/pkg
    ports: 
      - "${SHADOWSOCKS_PORT}:10086"
    networks:
      - frontend
      - backend
  golang:
    build:
      context: ./golang
    volumes:
      - ${DATA_PATH_HOST}/go/src:/go/src
      - ${DATA_PATH_HOST}/go/bin:/go/bin
      - ${DATA_PATH_HOST}/go/pkg:/go/pkg
    ports:
      - "8080:8080"
    networks:
      - frontend
      - backend
